---
name: WWW-WebArchive
version: 0.50
author:
  - spadkins@gmail.com
abstract: 'Recover files from the Internet Archive Wayback Machine (www.archive.org)'
license: perl
requires:
  App::Options:   0.01
  App::Trace:     0.01
  WWW::Mechanize: 0.01
provides:
  WWW::WebArchive:
    file: lib/WWW/WebArchive.pm
    version: 0.50
  WWW::WebArchive::Agent:
    file: lib/WWW/WebArchive/Agent.pm
  WWW::WebArchive::WaybackMachine:
    file: lib/WWW/WebArchive/WaybackMachine.pm
generated_by: hand
